### ISSUE TITLE
Errors are still shown in the console even if logged out

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5172]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

### Description

The console says:

```
Refined GitHub is only expected to work when you’re logged in to GitHub. Errors will not be shown.
```

But then it still shows errors:

<img width="783" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/145540553-cc5f4671-77b9-4172-832f-391de79cb250.png">

### Example URL

https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

### Browser(s) used

Firefox
