### ISSUE TITLE
🕊 Minor codebase updates and fixes

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5222]
Continues from https://github.com/refined-github/refined-github/pull/5213

This issue is not for generic bug reports but to suggest changes/refactoring to the extension itself.

**Comment by fregante** [comment]
- [ ] Automatically hide resolved comments on this issue and [#4008](https://github.com/refined-github/refined-github/issues/4008)

Both URLs can be hard-coded in the feature

<img width="644" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/146532721-f6a52833-09a1-4adb-979a-dda1d4c9c5f2.png">

**Comment by fregante** [comment]
Moved from https://github.com/refined-github/refined-github/pull/5213#pullrequestreview-833833784 https://github.com/refined-github/refined-github/issues/4008#issuecomment-812885528

- [ ] Maybe rewrite most `selector-observer` usage to use `deinit` instead of `onetime` as described in https://github.com/sindresorhus/refined-github/pull/4072#issuecomment-792402458
- [ ] add `deinit` to more features. Most `delegate` calls should result in a `deinit` on unload
- [ ] Make `init` return a specific type called `Deinit`, like:
   `type Deinit = VoidFunction | {abort: VoidFunction} | AbortController, etc` and then set the return value to `Deinit | Deinit[]`
   this will let us return values easily without having to locate the abort function of each
- [ ] Create a new `abortSignal` at every load and pass it to each `init`. This might be a little difficult to pass around at times, but it would be great to stop any async activity when unloading. For example addEventListener natively supports this signal so those features would not have to return anything:
	```js
	function init(signal: AbortSignal): void {
		document.body.addEventListener('click', doStuff, {signal})
	}
	```
	This case isn't better though:
	```js
	function init(signal: AbortSignal): void {
		const listener = delegate(..etc);
		signal.addEventListener('abort', listener.disconnect); 
	}
	```
	so it should just return `listener.disconnect` instead, as it's already possible
	```js
	function init(): Deinit {
		return delegate(..etc).disconnect;
	}
	```

**Comment by fregante** [comment]
- [ ] Automatically hide resolved comments on this issue and [#4008](https://github.com/refined-github/refined-github/issues/4008)

Both URLs can be hard-coded in the feature

<img width="644" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/146532721-f6a52833-09a1-4adb-979a-dda1d4c9c5f2.png">

**Comment by cheap-glitch** [comment]
- [ ] Clean up and rewrite `SearchQuery` so its side-effects are more contained

> SearchQuery is a mess, sorry about that. We try to parse, clean and update elements on creation. That’s a lot of side effects for a class. 
>
> The idea was to make it easy to update existing links, but perhaps we should avoid changing the original link until .commit() or .updateOriginal() is called. Alternative suggestions welcome.
>
> _Originally posted by @fregante in https://github.com/refined-github/refined-github/pull/5194#discussion_r769995937_

**Comment by fregante** [comment]
- [ ] Add alt-click to Screenshot links in the options. Rarely useful, but useful to review them as suggested in https://github.com/refined-github/refined-github/issues/5222#issuecomment-996620545

**Comment by fregante** [comment]
- [ ] Review some global CSS and especially github-bugs.css

Some of this code may be outdated. It may be as easy as:

1. Find page where code is meant to apply
2. Drop CSS rule
3. Do you see the bug the rule is meant to fix? Commit

**Comment by kidonng** [comment]
## Parse default branch, current committish and possibly other stuff from `<ref-selector>`

This element (actually, two) is available on `isRepoTree`.

Parsing info from it seems better than our current method([example](https://github.com/refined-github/refined-github/blob/3d06d1288e5c9739312fc61126f80e16bd501196/source/github-helpers/get-default-branch.ts#L26-L33)).

Note there are some issues with GitHub's code:

```ts
// https://github.githubassets.com/assets/app/assets/modules/github/ref-selector.ts

connectedCallback() {
    this.refType = this.getRequiredAttr('type') === 'branch' ? RefType.Branch : RefType.Tag
    const currentCommittishAttr = this.getAttribute('current-committish')
    this.currentCommittish = currentCommittishAttr ? atob(currentCommittishAttr) : null // Just `atob`?
    this.input = (this.hasAttribute('initial-filter') && this.currentCommittish) || ''
    this.defaultBranch = atob(this.getRequiredAttr('default-branch')) // Same here
    this.nameWithOwner = atob(this.getRequiredAttr('name-with-owner'))
    this.canCreate = this.hasAttribute('can-create')
    this.prefetchOnMouseover = this.hasAttribute('prefetch-on-mouseover')
    const queryEndpoint = this.getRequiredAttr('query-endpoint')
    const cacheKey = this.getRequiredAttr('cache-key')
    this.index = new SearchIndex(this.refType, this, queryEndpoint, cacheKey, this.nameWithOwner)
    this.setupFetchListeners()
  }
```

As you can see they only use `atob` to decode the string while in fact it can contain any Unicode[^1], so remember to wrap `decodeURIComponent(escape(string))` to get the correct result.

[^1]: some of our features are not Unicode-aware either

**Comment by fregante** [comment]
- [ ] Make our bug-report URLs field smaller via CSS (also via hotfix)

It's probably something like:

```css
#issue_form_example_urls, /* pre-click field */
#issue_form_example_urls + div textarea { /* also the WYSIWYG editor */
	min-height: 4em !important;
	height: 4em !plz;
}
```

The field is too big and I keep placing the description in it. We only need to be flexible in case we want to add multiple URLs.

<img width="863" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/157803993-45cba12d-8003-4151-963a-c76b0b901658.png">

**Comment by fregante** [comment]
- [ ] Create reusable `OptionsButton` component
- [ ] Make token notice in `rgh-improve-new-issue-form` less vague

Both described in https://github.com/refined-github/refined-github/pull/5457#pullrequestreview-910318623

**Comment by fregante** [comment]
- [ ] move the tests out of test and next to the related helpers, where possible, e.g. test/github-url.ts -> source/github-helpers/github-url.test.ts
	- [ ] extracting the pluralize/loose-parse-int out of `test/helpers.ts` into their own files (because they're already standalone helpers files)

**Comment by kidonng** [comment]
@fregante just a minor issue, could you replace the organization avatar with the transparent one? Organization avatars are shown in square and doesn't' look great with backgrounds.

**Comment by fregante** [comment]
It already is transparent

**Comment by fregante** [comment]
- [ ] Use API fetch forks in `forked-to`

https://github.com/refined-github/refined-github/pull/5597#issuecomment-1099167371

**Comment by cheap-glitch** [comment]
Maybe add the "user can merge this PR" check used in `wait-for-checks` to more PR merging features, like `sync-pr-commit-title`:

https://github.com/refined-github/refined-github/blob/9690ceb6430bb239ab71207ffa00fb9bee4f0fc1/source/features/wait-for-checks.tsx#L190-L191

**Comment by fregante** [comment]
- [ ] Move hotfixes to “live data” repo

We can do more than just disabling JS features and adding CSS. We could even have a way to change selectors on the fly in the future. 

- [ ] Add live data option in the repo; plus link and current status, e.g. “some CSS is being applied”. Disabled JS features already have UI for this.

**Comment by fregante** [comment]
- [ ] Add `rgh-quick-release` feature to redirect “Create release” link to the relevant Actions page 
- [ ] Propose new RGH meta features or just send a PR for them if small enough 😃

**Comment by fregante** [comment]
- [ ] Add these via `rgh-improve-new-issue-form` and drop them from `1_bug_report.yml`

<img width="236" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/176104899-7305cd95-45c3-4025-819b-06da6f963dea.png">


Not sure if it's worth it, but they're kinda noisy when looking at the issues, so it'd be great if they didn't appear there.

Alternatively we can just customize `1_bug_report.yml` so that this text only appears there. We can still use the `rgh-improve-new-issue-form` to make them more prominent. Checkboxes aren't required.

**Comment by fregante** [comment]
> Moved from #4008 

- [ ] Replace `exclude: [isEmptyRepo]` and related exclusions with a check in the `try init() catch` block in features/index. 

Instead of having to explicitly specify these exclusions, RG should just understand that the current page is incomplete and ignore every error. Maybe it should just show once a log: “This page is incomplete. Some features have been disabled.”

The feature logger might also display a log with a 💢 emoji or similar. 

Edit: Same goes for features that fail when you’re logged out.

**Comment by fregante** [comment]
- [ ] Wrap the debugging section in a `details` and add a background, more buttons may be coming
	- https://github.com/refined-github/refined-github/issues/5760
	- https://github.com/fregante/webext-options-sync/issues/23)

**Comment by fregante** [comment]
- [ ] Move https://github.com/refined-github/refined-github/blob/main/source/helpers/is-archived-repo.ts to https://github.com/refined-github/github-url-detection

**Comment by fregante** [comment]
- [ ] Disable `import/prefer-default-export` in `source/features/

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/blob/99c4eba5677b4ec271c854addc920ca8f27cb39d/source/options-storage.ts#L56:L56

**Comment by fregante** [comment]
- [ ] Fetch and immediately inject the hotfix CSS if available. 

Unlike the regular “disabled features” hotfix, CSS hotfixes can be injected at any time, so we can use `fetchCssHotfix().then(inject)` instead of using a separate `cache.get()`

Side note: my Safari 22.7.1 regularly loads pages without hotfix. We really need staleWhileRevalidate here.

**Comment by fregante** [comment]
- [ ] Drop `getRghIssueUrl`, it just saves a few characters but makes these URLs not clickable in the IDE and in the browser

**Comment by fregante** [comment]
- [ ] Update https://github.com/refined-github/github-url-detection/issues/133

**Comment by fregante** [comment]
- [ ] Use `showToast` in `update-pr-from-base-branch`

Any more features that show the status inline?

**Comment by fregante** [comment]
- [ ] Replace all/most custom listeners like `onFileLoad` with the new selector observer as it's the most efficient, safe and easy to use solution

**Comment by fregante** [comment]
- [ ]  replace most of its `isRepo` calls with `hasRepoHeader`


From: https://github.com/refined-github/github-url-detection/pull/131

Trying not to break https://github.com/refined-github/refined-github/issues/5739 again.

**Comment by fregante** [comment]
- [ ] Add a workflow to lint other workflows https://github.com/rhysd/actionlint

Kind annoying that GitHub doesn't do this natively and it only complains when it actually runs the workflow (particularly a problem for the release workflow, which only runs on `main`)
