### ISSUE TITLE
`rgh-feature-description` not working on weird url

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5471]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

```
https://github.com/refined-github/refined-github/blob/main/source%2Ffeatures%2Frestore-file.tsx
```

### Extension version

22.2.13

### Browser(s) used

Safari 15.3

### Description

1. Visit https://github.com/refined-github/refined-github/find/main
2. Type "restore"
3. open `restore-file`
4. See no feature and weird URL encoding

<img width="1273" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/157279734-dd210dd3-c182-4138-a7a0-4521c927ef43.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by yakov116** [comment]
https://github.com/refined-github/refined-github/issues/5470
