### ISSUE TITLE
"Find a feature" not able to find what is removing fork counts

### ISSUE THREAD

**Issue by asmeurer** [refined-github/refined-github#5666]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/sympy/sympy

### Extension version

22.5.22

### Browser(s) used

Google Chrome on macOS

### Description

Some feature of refined GitHub is removing the count of the number of forks at the top of the page on a repo I contribute to. See the screenshots below

**Extension disabled**
<img width="717" alt="Screen Shot 2022-05-31 at 2 25 41 PM" src="https://user-images.githubusercontent.com/71486/171278946-63f11cb7-0011-4410-96e9-3a40aa49d3bf.png">
**Extension enabled**
<img width="624" alt="Screen Shot 2022-05-31 at 2 25 32 PM" src="https://user-images.githubusercontent.com/71486/171278947-68393866-8210-4c4a-8c41-1bde9a245778.png">
 
I tried using the "find a feature" debugging feature to figure out what is doing this, but every round still has the forks number hidden, leaving it to state that it is not being caused by the extension. But it is being caused by it somehow because the count is there when I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/issues/5668
