### ISSUE TITLE
`unfinished-comments` is incorrectly triggered when (un)checking a todo-list item

### ISSUE THREAD

**Issue by filiptronicek** [refined-github/refined-github#5695]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/open-vsx/publish-extensions/pull/597

### Extension version

22.5.22

### Browser(s) used

Firefox

### Description

When an issue has todos, you can tick or untick them interactively using the UI, but if you end up doing that, you always get that you are now drafting a comment in the page's title. The ticking and unticking is saved immediately, so this should not happen.

### Include in this issue:

- [x] Screenshots/video/gif demonstrating the bug, if it’s visual
- [x] Console errors, if any

**Comment by fregante** [comment]
Good catch! Confirmed

**Comment by fregante** [comment]
The feature still works and can no longer reproduce 🎉 

![ko](https://user-images.githubusercontent.com/1402241/217816194-c70a7634-d981-4a8c-9ebe-2d90d171d8a9.gif)
