### ISSUE TITLE
:has() selector discussion

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5797]
Feel free to leave a comment (or more) if you think of any features that can be rewritten or enhanced using the `has` selector. 

Live examples:

- https://github.com/refined-github/refined-github/pull/5795
- https://github.com/refined-github/refined-github/issues/5757#issuecomment-1177997611

But also, maybe:

- [ ] hiding tabs that have a zero (the number is often in an attribute as well, so it can be targeted)
- [ ] hiding events from the newsfeed
- [ ] showing our “update branch” button if the native button doesn’t exist, dynamically, without events! We append the link and just use `body:has(native button) .our-button {hide}` 🤯 

I swear this selector is a game changer for extensions. The only thing it can’t do is *alert us* of such events (maybe 😏 via empty `animationend` on these elements + JS listener)

**Comment by fregante** [comment]
Chrome will see this on August 30, version 105:

- https://chromestatus.com/feature/5794378545102848
- https://chromiumdash.appspot.com/schedule

Also new `has`-only feature coming:

- https://github.com/refined-github/refined-github/pull/5858

**Comment by fregante** [comment]
It is August 30th.

All new features and "restored features" can use `:has()`

Firefox will follow at some point. Tracking issues:

- https://bugzilla.mozilla.org/show_bug.cgi?id=418039
- it seems that it's been implemented, but still buggy and off by default https://news.ycombinator.com/item?id=32533720

**Comment by jerone** [comment]
Please wait until Firefox has full support for `has`.
There are already [3 features](https://github.com/refined-github/refined-github/search?l=CSS&q=has) that use `has` in CSS. 
One of which I wanted to propose, only to found out it [already exists](https://github.com/refined-github/refined-github/blob/3996cc453ca530c441bda87235b4dda383b46cbb/source/features/readable-title-change-events.css#L3), but just doesn't work on Firefox.

**Comment by fregante** [comment]
As mentioned, new features and bugfixes *can* already use the new selector. Firefox will get them whenever they'll get them. We're not going to retroactively break features, so it's ok.

**Comment by fregante** [comment]
Possible new selector usage:


- [ ] CSS-only `dim-bots`, except for a possible ["expand bots" JS listener](https://github.com/refined-github/refined-github/pull/5946#pullrequestreview-1100448376)
- [ ] New hide repeated issue events https://github.com/refined-github/refined-github/issues/615#issuecomment-507524375

**Comment by FloEdelmann** [comment]
@jerone By the way, you can opt-in to Firefox's preliminary implementation by enabling the `layout.css.has-selector.enabled` rule in `about:config` (see https://caniuse.com/css-has), which seems to work fine for these three RGH features.

**Comment by jtagcat** [comment]
Note: `layout.css.has-selector.enabled` also requires a restart.

`unhide-reactions-on-mobile` (#6182) now also uses `:has`.

**Comment by pradyunsg** [comment]
Hmm... Firefox doesn't seem to have moved any closer on this in the last 6 months; based on the activity on the tracking issue and hide-own-stars' fix is not compatible with Firefox's experiemental implementation.

Is there a suggested workaround for Firefox users, since currently, we're getting a degraded experience (even after enabling the experimental flag)?

**Comment by fregante** [comment]
Unfortunately not. GitHub has also been making changes to their DOM making it increasingly difficult to target elements reliably, which means I have no choice but use `has()`

**Comment by fregante** [comment]
<img width="392" alt="Screenshot 2" src="https://user-images.githubusercontent.com/1402241/212818223-29e4dd14-f5c7-4793-90e2-bca14ef07a9f.png">

Which probably means 12 more months of no "has"

**Comment by jtagcat** [comment]
You meant 4-5 years later? (:

**Comment by nitzcard** [comment]
it works if I do this for the moment: 
about:config -> <img width="688" alt="image" src="https://github.com/refined-github/refined-github/assets/123297447/00296563-3504-45b5-95ed-e130bb8198d2">

until firefox will support :has :)

**Comment by fregante** [comment]
Upstream bug closed! Coming to Firefox 119 on October 2024

- https://bugzilla.mozilla.org/show_bug.cgi?id=1853701
- https://whattrainisitnow.com/calendar/

We can start fixing all the TODOs (but they won't be merged until that date)

**Comment by jerone** [comment]
> Firefox 119 on October 2024

2023 you probably mean.

**Comment by FloEdelmann** [comment]
2023-10-24

**Comment by fregante** [comment]
* October 24th

**Comment by fregante** [comment]
New issue to track:

- https://bugzilla.mozilla.org/show_bug.cgi?id=418039

Apparently on hold until at least Firefox v121, December 19th. It's strange because it already passes the [web interop tests](https://wpt.fyi/results/css/selectors/dir-pseudo-in-has.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=subtest&q=label%3Ainterop-2023-pseudos) 10x faster than Chrome, even.

Anyway presumably this already works well if you enable the `layout.css.has-selector.enabled`, so if you're here you can already enjoy the latest features. 🚀 

See you in 2024 guys

**Comment by marvinhagemeister** [comment]
FWIW: the usage of `:has()` in the current code breaks the Refined GitHub extension for all Firefox users.

<img width="784" alt="Screenshot 2023-11-06 at 20 45 06" src="https://github.com/refined-github/refined-github/assets/1062408/9107d8f7-024f-4ecc-b4ca-ed304183366b">

**Comment by fregante** [comment]
An error message doesn't mean the whole extension is broken. It's just an error message, other features are not affected.

Duplicate of https://github.com/refined-github/refined-github/issues/7035

**Comment by marvinhagemeister** [comment]
For me it does render all code differently, because for some reason it falls back to a sans-serif font instead of monospace. When I disable the extension, code is rendered correctly with a monospace font as expected.

**Comment by fregante** [comment]
> it does render all code differently, because for some reason it falls back to a sans-serif font instead of monospace.

I'd like to see a full bug report for that and whether it works after you enable the flag in `about:config`

**Comment by ChaseKnowlden** [comment]
Firefox 121 is releases!

https://archive.mozilla.org/pub/firefox/releases/121.0/

**Comment by fregante** [comment]
We'll likely still wait a few weeks before releasing a release that breaks Firefox <120.

> _On January 17 2023 @fregante wrote:_
> 
> Which probably means 12 more months of no "has"

It turned out just about right 😃

**Comment by fregante** [comment]
Can be closed. I cleaned up past polyfills and some TODOs. Due to performance issues, `:has()` cannot be used on large elements. This is quite unfortunate because of the benefits that moving logic to the CSS for extensions and userstyles would bring.
