### ISSUE TITLE
🥉 Minor codebase updates and fixes

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6000]
Congrats! I'm gonna use this issues as a placeholder for the next #5222 issue 😌 

plz don't comment or add labels.

If you see this issue, you will have 56 years of good luck.

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/issues/5222 is starting to hide some events in the middle, so I'll start adding more items here:

- [ ] Update `@primer/octicons-react` (17.11 breaks dom-chef)

https://github.com/refined-github/refined-github/pull/6326/files#r1103554022

**Comment by fregante** [comment]
- [ ] Fix some TODOs 
- [ ] Review and update ancient screenshots, e.g. https://user-images.githubusercontent.com/1402241/54178764-d1c96080-44d1-11e9-889c-734ffd2a602d.png

Gifs may be left unchanged because they're harder to replicate.

**Comment by fregante** [comment]
- [ ] Revert https://github.com/refined-github/refined-github/pull/3208

This works now in Firefox 🎉 

```js
Object.getPrototypeOf(new (class extends URL {method() {}})(location.href)).method
```

Context: https://github.com/refined-github/refined-github/issues/3193#issuecomment-93760

Screenshot: https://github.com/refined-github/refined-github/assets/1402241/91d43f7b-54b8-459a-b851-bd2a3650ca40

cc @kidonng

**Comment by fregante** [comment]
- [ ] Use `SearchQuery` in most places where we build/alter search queries.

Examples: https://github.com/search?q=repo%3Arefined-github%2Frefined-github+%2Fis%3Aissue%2F&type=code

**Comment by fregante** [comment]
- [ ] Use `experiments.css` in webpack: https://webpack.js.org/configuration/experiments/#experimentscss

> CSS extraction: webpack will extract CSS into a separate file. This functionality replaces the need for mini-css-extract-plugin and css-loader, as it provides native support.

**Comment by fregante** [comment]
- [ ] Show the username of the entered token (as part of the scope check UI)

**Comment by fregante** [comment]
- [ ] Correctly support URLs like `https://github.com/refined-github/refined-github/assets/50487467/747b5133-61b8-490e-b961-4e5390ea9482` in the readme-parser and feature validator. Currently they're silently ignored

Seen in https://github.com/refined-github/refined-github/pull/6900#pullrequestreview-1621264680

**Comment by fregante** [comment]
- [ ] Add waitForChildren to the selector observer


See https://github.com/sindresorhus/element-ready/issues/29. Occasionally we need to ensure the full element has been loaded and we already have some workarounds for that, for example in #6909

**Comment by fregante** [comment]
- [ ] Document CSS features in readme as well, so that they can be linkified. Example: `clean-checks-list`. Features can be documented there and hidden via `<!-- -->` if necessary
- [ ] Update `rgh-feature-descriptions` to show this description
- Add check to `verify-features.ts` to ensure every .css feature
	- [ ] is documented in readme
	- [ ] has test URLs

**Comment by fregante** [comment]
- [ ] Move Contributing.md to the wiki

https://github.com/refined-github/refined-github/blob/main/contributing.md

**Comment by fregante** [comment]
- [ ] Convert some selectors to used Nested Selectors (for clarity and to avoid repetition)

Originally tracked in https://github.com/refined-github/refined-github/issues/6665

**Comment by fregante** [comment]
- [ ] Mark more features with "expect token" helper so that we don't get these errors

<img width="553" alt="Screenshot 4" src="https://github.com/refined-github/refined-github/assets/1402241/a4cdd3db-166e-4311-824e-c0e6179654d5">

**Comment by fregante** [comment]
- [ ] Show current version in the options page, probably under debugging

On iOS Safari it’s really difficult to find the version of the extension, so we should show it in the options page.

**Comment by fregante** [comment]
- [ ] Detect locked issues via API

We're using the DOM to detect them but this is something we can ask the API with 100% confidence.

Will fix:

https://github.com/refined-github/refined-github/blob/5370d0e67ad1f43f9416d49464cf7b0db9da30f3/source/features/locked-issue.tsx/#L46-L50

**Comment by fregante** [comment]
- [ ] Hotfixed features should not be mixed with user-disabled features

1. user-disabled features
2. hotfix-disabled features 
3. enabled features

<img width="692" alt="Screenshot 8" src="https://github.com/user-attachments/assets/1d03d6a6-c15a-4233-8c53-dbf01725b090">
