### ISSUE TITLE
Make hotfixes visible in options

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6383]
- [ ] Let the user disable hotfixes (default to `false` on `isDevelopmentVersion`)
- [ ] Disable access to 1_bug_report.yml if hotfixes have been disabled 
- [x] Display status of CSS hotfixes (have any been loaded?)
- [x] Add buttons to fetch new hotfixes

_Originally in https://github.com/refined-github/refined-github/issues/5222#issuecomment-1167741255_

**Comment by fregante** [comment]
> * [ ]  Let the user disable hotfixes (default to `false` on `isDevelopmentVersion`)

This hasn't been an issue in practice. The idea was to be able to expose the logic to "development version" users, but this would require deployment changes that I don't want to look into right now (i.e. update the version in `manifest.json` via commit in `release.yml`)
