### ISSUE TITLE
Improve feature verification

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7132]
Most important of all:

- [x] I think we should move the verification to go through Vitest. It will probably look like:
	```js
	describe('features', () => {
		for (const feature of getFeatureMeta() {
			test(feature.id, () => {
				// our current tests, but using assert instead of `return "ERR:"`
			})
		}
	});
	```

- [ ] Document CSS features in readme as well, so that they can be linkified. Example: `clean-checks-list`. Features can be documented there and hidden via `<!-- -->` if necessary
- [ ] Update `rgh-feature-descriptions` to show this description
- [ ] Add check to `verify-features.ts` to ensure every .css feature
	- [ ] is documented in readme
	- [x] has test URLs
	- [x] _does not_ have Test URLs if it has a .tsx sibling
- [x] Move renames to renames.json
- [x] Verify renames in renames.json
	- [x] Old feature names cannot appear anywhere (use `grep`)
	- [x] New feature names must exist

_Originally posted by @fregante in https://github.com/refined-github/refined-github/issues/6000#issuecomment-1730674889_

**Comment by fregante** [comment]
The CSS test-urls check was attempted in https://github.com/refined-github/refined-github/commit/1b7b182867e6d5d81fef1281d70c8f5b88e1bf22 but was not finalized. It can be continued there.

**Comment by fregante** [comment]
The test URLs check is failing on the GitHub bugs CSS file: https://github.com/refined-github/refined-github/pull/7189

- [ ] exclude that file

**Comment by fregante** [comment]
Will move CSS documentation to its own issue
