### ISSUE TITLE
Mark more clearly that the token is "required"

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7231]
Every so often someone is confused as to why some features don't work. Since features vary over time and occasionally start requiring the token, people are further confused as to why they stop working.

This makes no sense and I don't want to support token-less usage anymore. People can continue to use RG without it, but then we don't want to waste time figuring that out.

Why?

- the token can be read-only and limited to public repos
- our permissions already only target GitHub.com

Changes suggested:

- [x] Update wording in [welcome issue](https://togithub.com/refined-github/refined-github/issues/3543)
- [x] https://github.com/refined-github/refined-github/issues/7382
- [x] Improve wording in options page to suggest the above
- [ ] Show a block screen on the bug report page to invite people to use the token before opening an issue. I'm not sure if this screen can be made closeable (to allow people to report real bugs) or not (to block people from reporting token-related non-bugs)

Related:

- https://github.com/refined-github/refined-github/issues?q=+to+set+the+token+in%3Atitle
- https://github.com/refined-github/refined-github/issues/7163#issuecomment-1909923561
- https://github.com/refined-github/refined-github/pull/7221#issuecomment-1894910985
