### ISSUE TITLE
Help add test URLs to the last features

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7656]
1. Pick a handful at random
2. Collect some test URLs in the PRs (drop `in:title` from the search if it's empty)
3. Add
4. Open a single PR with the selected features

Features:

- [ ] `action-used-by-link` - [search](https://github.com/refined-github/refined-github/pulls?q=%22action-used-by-link%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `align-issue-labels` - [search](https://github.com/refined-github/refined-github/pulls?q=%22align-issue-labels%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `clean-pinned-issues` - [search](https://github.com/refined-github/refined-github/pulls?q=%22clean-pinned-issues%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `command-palette-navigation-shortcuts` - [search](https://github.com/refined-github/refined-github/pulls?q=%22command-palette-navigation-shortcuts%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `comment-fields-keyboard-shortcuts` - [search](https://github.com/refined-github/refined-github/pulls?q=%22comment-fields-keyboard-shortcuts%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `convert-pr-to-draft-improvements` - [search](https://github.com/refined-github/refined-github/pulls?q=%22convert-pr-to-draft-improvements%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `cross-deleted-pr-branches` - [search](https://github.com/refined-github/refined-github/pulls?q=%22cross-deleted-pr-branches%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `emphasize-draft-pr-label` - [search](https://github.com/refined-github/refined-github/pulls?q=%22emphasize-draft-pr-label%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `esc-to-cancel` - [search](https://github.com/refined-github/refined-github/pulls?q=%22esc-to-cancel%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `esc-to-deselect-line` - [search](https://github.com/refined-github/refined-github/pulls?q=%22esc-to-deselect-line%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `extend-conversation-status-filters` - [search](https://github.com/refined-github/refined-github/pulls?q=%22extend-conversation-status-filters%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `extend-diff-expander` - [search](https://github.com/refined-github/refined-github/pulls?q=%22extend-diff-expander%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `global-conversation-list-filters` - [search](https://github.com/refined-github/refined-github/pulls?q=%22global-conversation-list-filters%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `hide-diff-signs` - [search](https://github.com/refined-github/refined-github/pulls?q=%22hide-diff-signs%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `hide-issue-list-autocomplete` - [search](https://github.com/refined-github/refined-github/pulls?q=%22hide-issue-list-autocomplete%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `hide-newsfeed-noise` - [search](https://github.com/refined-github/refined-github/pulls?q=%22hide-newsfeed-noise%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `html-preview-link` - [search](https://github.com/refined-github/refined-github/pulls?q=%22html-preview-link%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `improve-shortcut-help` - [search](https://github.com/refined-github/refined-github/pulls?q=%22improve-shortcut-help%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `keyboard-navigation` - [search](https://github.com/refined-github/refined-github/pulls?q=%22keyboard-navigation%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `linkify-commit-sha` - [search](https://github.com/refined-github/refined-github/pulls?q=%22linkify-commit-sha%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `linkify-labels-on-dashboard` - [search](https://github.com/refined-github/refined-github/pulls?q=%22linkify-labels-on-dashboard%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `linkify-user-edit-history-popup` - [search](https://github.com/refined-github/refined-github/pulls?q=%22linkify-user-edit-history-popup%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `more-conversation-filters` - [search](https://github.com/refined-github/refined-github/pulls?q=%22more-conversation-filters%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `no-duplicate-list-update-time` - [search](https://github.com/refined-github/refined-github/pulls?q=%22no-duplicate-list-update-time%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `one-key-formatting` - [search](https://github.com/refined-github/refined-github/pulls?q=%22one-key-formatting%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `patch-diff-links` - [search](https://github.com/refined-github/refined-github/pulls?q=%22patch-diff-links%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `pr-branch-auto-delete` - [search](https://github.com/refined-github/refined-github/pulls?q=%22pr-branch-auto-delete%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `prevent-duplicate-pr-submission` - [search](https://github.com/refined-github/refined-github/pulls?q=%22prevent-duplicate-pr-submission%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `prevent-pr-merge-panel-opening` - [search](https://github.com/refined-github/refined-github/pulls?q=%22prevent-pr-merge-panel-opening%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `pull-request-hotkeys` - [search](https://github.com/refined-github/refined-github/pulls?q=%22pull-request-hotkeys%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `rgh-welcome-issue` - [search](https://github.com/refined-github/refined-github/pulls?q=%22rgh-welcome-issue%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `same-branch-author-commits` - [search](https://github.com/refined-github/refined-github/pulls?q=%22same-branch-author-commits%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `scrollable-areas` - [search](https://github.com/refined-github/refined-github/pulls?q=%22scrollable-areas%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `show-user-top-repositories` - [search](https://github.com/refined-github/refined-github/pulls?q=%22show-user-top-repositories%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `stop-redirecting-in-notification-bar` - [search](https://github.com/refined-github/refined-github/pulls?q=%22stop-redirecting-in-notification-bar%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `submission-via-ctrl-enter-everywhere` - [search](https://github.com/refined-github/refined-github/pulls?q=%22submission-via-ctrl-enter-everywhere%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `tab-to-indent` - [search](https://github.com/refined-github/refined-github/pulls?q=%22tab-to-indent%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `toggle-everything-with-alt` - [search](https://github.com/refined-github/refined-github/pulls?q=%22toggle-everything-with-alt%22+is%3Aclosed+is%3APR+in%3Atitle)
- [ ] `warn-pr-from-master` - [search](https://github.com/refined-github/refined-github/pulls?q=%22warn-pr-from-master%22+is%3Aclosed+is%3APR+in%3Atitle)

I'll update the list via:

```
build/verify-test-urls.sh source/features/*.tsx | grep '❌'
```

**Comment by fregante** [comment]
It would be good to also add a `/* Test: https:// etc etc */` for each rule in GitHub-bugs.scss. Some rules are hard to test, even though they have PR references.


### Good

https://github.com/refined-github/refined-github/blob/eb38d85e29a023620880d98ce38f0bb2ba0eec8a/source/features/github-bugs.css/#L36-L40

### No good

Both issue reference an test URL missing

https://github.com/refined-github/refined-github/blob/eb38d85e29a023620880d98ce38f0bb2ba0eec8a/source/features/github-bugs.css/#L31-L34
