### ISSUE TITLE
Custom code lint ideas

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7720]
Following up from:

- #7696 

My suggestions:

- [ ] Enforce `title="Hotkey: ..."` if `data-hotkey` is found (like in https://github.com/refined-github/refined-github/pull/7719/files)
- [x] Block usage of `?.` or require explanation via eslint-comment-disable
- [x] Block usage of `$()!.`, enforce `expectElement()`

What other common small code issues  can we can automate via custom ESLint rules?

PR welcome to add any rule suggested in this thread, as done in #7696.
