### ISSUE TITLE
We should also add comments for each rule in `github-bugs.css` and `refined-github.css`. Some rules are hard to test, even though they have PR references.

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7758]
- Continues from https://github.com/refined-github/refined-github/issues/7656
- Continues from https://github.com/refined-github/refined-github/issues/7132

## Tasks

- [ ] Add test URLs to `refined-github.css` and `github-bugs.css` (see below)
- [ ] Document CSS-only feature files in readme as well, so that they can be linkified. Example: `clean-checks-list`. Features can be documented there and hidden via `<!-- -->` if necessary
- [ ] Update `rgh-feature-descriptions` to show this description
- [ ] Add check to `verify-features.ts` to ensure every CSS-only feature  is documented in readme

## refined-github.css

Some rules are hard to test, even though they have PR references, here's what they should look like:

### Good

https://github.com/refined-github/refined-github/blob/eb38d85e29a023620880d98ce38f0bb2ba0eec8a/source/features/github-bugs.css#L36-L40

### No good

Both issue reference an test URL missing

https://github.com/refined-github/refined-github/blob/eb38d85e29a023620880d98ce38f0bb2ba0eec8a/source/features/github-bugs.css#L31-L34

_Originally posted by @fregante in https://github.com/refined-github/refined-github/issues/7656#issuecomment-2294855975_
