### ISSUE TITLE
⚠️ Features broken on new commit view page (beta)

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7808]
### Description

https://github.blog/changelog/2024-09-18-new-commit-details-page-public-beta/

Some features are surely broken here, like our diff/patch links. 

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/commit/2583024c7f8eb01ebd74d339849f1d551af80c70

### Extension version

24.8.20

### Browser(s) used

Safari

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by elmaxe** [comment]
The tag preview next to commits also seems to be broken with the beta turned on

https://github.com/orgs/community/discussions/139005#discussioncomment-10694056

**Comment by jdreesen** [comment]
For me, `patch-diff-links` is broken:

> 12:57:46.803 📕 24.8.30 → TypeError: commitMeta is undefined

Browser: Firefox 130

**Comment by fregante** [comment]
PR welcome 🙏

**Comment by jdreesen** [comment]
It's actually more than that:
![grafik](https://github.com/user-attachments/assets/b6c295b6-668a-4572-ad29-1d2cefcc80be)
I'll see if I can create a PR in the next few days.

**Comment by fregante** [comment]
This is the full list of features running on single commit and commit list pages. PR Commit views are tracked separately: https://github.com/refined-github/refined-github/issues/7988

Some of these are a bit harder to verify because we don't have test links, specifically those around "comments on commits". Honestly we can just skip all features related to that view because it's rare, complex and undesirable (#7571) anyway.


For the record, here's a test link: https://github.com/refined-github/sandbox/commit/54c10fe670779eab43b6a18b7fb06e51dd7050af#r148774860

Important or easy:

- [x] `reactions-avatars`
- [x] `keyboard-navigation`
- [x] `pagination-hotkey`
- [x] `toggle-everything-with-alt`

Medium:

- [ ] `no-unnecessary-split-diff-view`
- [ ] `parse-backticks`
- [ ] `preview-hidden-comments`
- [x] `more-file-links`

Difficult:
- [ ] `show-whitespace` - see https://github.com/refined-github/refined-github/issues/7843
- [ ] `quick-comment-edit` - see #7893 
- [ ] `linkify-code` - see #6336 
- [ ] `new-or-deleted-file` - see https://github.com/refined-github/refined-github/issues/6741


No longer relevant:

- [ ] `prevent-comment-loss` 👋
- [ ] `quick-comment-hiding` 👋

55+ working features already removed from the list

**Comment by tonglil** [comment]
Adding [`remove-diff-signs`](https://github.com/refined-github/refined-github/blob/main/source/features/hide-diff-signs.tsx)

<img width="913" alt="image" src="https://github.com/user-attachments/assets/4d4a841e-d5a5-4113-a0ea-863a5b3f9386">

**Comment by alexanderniebuhr** [comment]
For me `conventional-commits` seems to be broken completely, however looking at the list above it should work.

**Comment by fregante** [comment]
So it looks like there are only 8 broken features now, the rest of them already have a dedicated issue.

This is thanks to the great work done by @kovsu! 💥

**Comment by kiprasmel** [comment]
the suggestion button is also not available.

**Comment by fregante** [comment]
Unrelated to Refined GitHub and to commit view in title. That's the PR view and that's a native feature.

**Comment by kiprasmel** [comment]
correct. but until github fixes it, couldn't we add that button ourselves? (sorry for unrelated)

**Comment by fregante** [comment]
No

This thread is about broken _Refined GitHub_ features. Please refrain from requesting new features here.

**Comment by fregante** [comment]
Most have been fixed, closing. 

If you find any broken feature, please open a regular bug report.
