### ISSUE TITLE
`rgh-*` features broken on new beta views

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#8012]
I listed all the private features:

- [x] `rgh-linkify-features`
	- Maybe related to https://github.com/refined-github/refined-github/issues/7856
- [ ] `rgh-netiquette`
	- ~~Related to and maybe fixed by https://github.com/refined-github/refined-github/pull/8010~~
- [x] `rgh-dim-commits`
	- Related to https://github.com/refined-github/refined-github/issues/7808
- [x] `rgh-feature-descriptions`
- [x] `rgh-options-link`
- [x] `rgh-improve-new-issue-form`
- [x] `rgh-linkify-yolo`
- [x] `rgh-pr-template`
- [x] `rgh-token-user`

Those unchecked are broken or not yet checked on the new views.

**Comment by fregante** [comment]
Only `rgh-netiquette` is broken now. It doesn't affect the repo yet because I haven't enabled the beta, but eventually it will come. It's best that this feature works by then.

cc @kovsu if you want to take a look.

1.  Disable `netiquette`
2. Remove `isAnyRefinedGitHubRepo` from the requirements of `rgh-netiquette`
3. Open https://github.com/download-directory/download-directory.github.io/issues/74
